# Generated by Django 2.1.3 on 2018-11-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='when',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
