# Generated by Django 2.1.3 on 2018-11-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20181111_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
