# Generated by Django 2.0 on 2018-11-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_auto_20181111_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='trip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='benefactor',
            field=models.CharField(max_length=100),
        ),
    ]
