# Generated by Django 2.0 on 2018-11-11 09:59

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0007_auto_20181111_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefactor',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='benefactor',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='benefactor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='trip',
        ),
        migrations.AddField(
            model_name='benefactor',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='benefactor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cost',
            name='benefactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.Trip'),
            preserve_default=False,
        ),
    ]
