# Generated by Django 2.0 on 2018-11-11 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_auto_20181111_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefactor',
            options={},
        ),
        migrations.AlterModelManagers(
            name='benefactor',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='benefactor',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benefactor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
