# Generated by Django 2.0 on 2018-11-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_auto_20181111_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefactor',
            name='admin',
        ),
    ]
