# Generated by Django 2.0 on 2018-11-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0011_remove_benefactor_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefactor',
            name='user',
        ),
        migrations.AddField(
            model_name='benefactor',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
